on: 
  schedule:
      - cron: '*/5 * * * *'
jobs:
  first_job:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: '3.8'
      - name: Run
        run: python c3.py
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_NAME: ${{ secrets.DB_NAME }}

